---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  labels:
    app: wp-secret
type: Opaque
data: 
  ROOT_PASSWORD: Y2hhbmdlaXQ= 
  WORDPRESS_DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm
  labels:
    name: wp-cm
data:
  WORDPRESS_DB_HOST: wpdb-cluster-mysql-master
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: wpdb
---