---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels: 
    app: bgg

spec:
  type: ClusterIP
  selector:
    app: bgg
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels: 
    app: bgg
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: bgg
    tier: backend
  ports:
  - port: 8080
    targetPort: 3000
---